name: "Ansible"
description: "Runs an Ansible playbook"
inputs:
  playbook:
    required: true
    default: 'deploy.yml'
  inventory:
    required: true
    default: 'production'
  vault_pass:
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.playbook }}
    - ${{ inputs.inventory }}
    - ${{ inputs.vault_pass }}
